ALTER TABLE users ADD COLUMN notify_on_request_created BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN notify_on_prayed BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN notify_on_answered BOOLEAN NOT NULL DEFAULT TRUE;
